<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/20
 * Time: 17:02
 */

namespace app\admin\model;

use \think\Model;

class AdminBase extends Model {
  protected function initialize() {
    parent::initialize(); // TODO: Change the autogenerated stub
  }
  protected static function init() {
    parent::init(); // TODO: Change the autogenerated stub
  }

}
