<?php

namespace app\admin\controller;

use app\admin\model\AuthGroupRuleModel;
use app\common\controller\AdminBaseController;
use think\Request;

class AdminController extends AdminBaseController {
  protected
  function _initialize() {
    parent::_initialize(); // TODO: Change the autogenerated stub
  }

  /*GET  blog*/
  public
  function index() {
    $a=new AuthGroupRuleModel();
    $a->getGroups();
    dump( 1111);
    return $this->fetch();
  }

  /*GET  blog/create*/
  public
  function create() {
    return $this->fetch();
  }

  /*POST  blog*/
  public
  function save() {
  }

  /*GET  blog/:id*/
  public
  function read() {
    return $this->fetch();
  }

  /*GET  blog/:id/edit*/
  public
  function edit() {
    return $this->fetch();
  }

  /*PUT  blog/:id*/
  public
  function update() {
  }

  /*DELETE  blog/:id*/
  public
  function delete() {
  }
}
