<?php

namespace app\admin\controller;

use app\common\controller\AdminBaseController;
use think\Request;

class AdminController extends AdminBaseController {
  protected
  function _initialize() {
    parent::_initialize(); // TODO: Change the autogenerated stub
  }

  public
  function lists() {
    return $this->fetch();
  }

  public
  function add() {
    return $this->fetch();
  }

  public
  function edit() {
    return $this->fetch();
  }

  public
  function delete() {
    return $this->fetch();
  }

  public
  function sort() {
    return $this->fetch();
  }

  public
  function test() {
    return $this->fetch('public@/html/index');
  }
}
