<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/22
 * Time: 14:34
 */

namespace app\admin\controller;


use app\common\controller\AdminBaseController;

class LoginController extends AdminBaseController {
  protected function _initialize() {
    parent::_initialize(); // TODO: Change the autogenerated stub
  }
}