<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/7
 * Time: 15:50
 */

namespace app\admin;



use app\admin\controller\AdminBase;

class Resource extends AdminBase {
  protected
  function _initialize() {
    parent::_initialize(); // TODO: Change the autogenerated stub
  }

  /*GET  blog*/
  public
  function index() {

  }

  /*GET  blog/create*/
  public
  function create() {
  }

  /*POST  blog*/
  public
  function save() {
  }

  /*GET  blog/:id*/
  public
  function read() {
  }

  /*GET  blog/:id/edit*/
  public
  function edit() {
  }

  /*PUT  blog/:id*/
  public
  function update() {
  }

  /*DELETE  blog/:id*/
  public
  function delete() {
  }
}
