<?php
namespace app\common\controller;

use think\Response;

class AdminBaseController extends AppController {
    protected function _initialize() {
      parent::_initialize(); // TODO: Change the autogenerated stub
    }

    protected function ajaxReturn($code,$msg,$data,$type='json'){
      $result=[
        'code'=>$code,
        'msg'=>$msg,
        'data'=>$data
      ];

      switch (strtolower( $type)){
        case 'json':{
          $result=Response::create( $result,'json');
          break;
        }
        case 'jsonp': {
          $result = Response::create( $result, 'jsonp' );
          break;
        }
        case 'xml': {
          $result = Response::create( $result, 'xml' );
          break;
        }
        case 'array':
        default:{
          $result = Response::create( $result, 'json' );
          break;
        }
      }
      return $result;
    }
}
