<?php
namespace app\common\controller;

class AdminBaseController extends AppController {
    protected function _initialize() {
      parent::_initialize(); // TODO: Change the autogenerated stub
    }
}
