<?php
namespace app\common\controller;

use think\Controller;

class AppController extends Controller {

  protected function _initialize() {
    parent::_initialize(); // TODO: Change the autogenerated stub


  }

}
