<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/28
 * Time: 9:56
 */

namespace app\common\controller;


use think\App;

class PortalBaseController extends AppController {


  protected
  function _initialize() {

    /*获取模板设置*/
    $template = config( 'template' );
    /*设置模板临时缓存目录*/
    $template[ 'cache_path' ] = TEMP_PATH . $this->module . DS . $this->controller . DS;
    /*设置模板缓存*/
    if ( !App::$debug ) {
      $template[ 'cache_id' ] = md5( $this->module . DS . $this->controller . DS . $this->action );
      $template[ 'display_cache' ] = true;
    }
    /*设置模板视图根目录*/
    $template[ 'view_base' ] = THEME_PATH . 'portal' . DS . config( 'theme.portal_theme' ) . DS;
    /*设置模板引擎*/
    $this->engine( $template );

    $this->viewReplaceStr = array_merge( $this->viewReplaceStr,
                                         [
                                           "__PORTAL_STATIC__"  => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static',
                                           "__PORTAL_JS__"      => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static/js',
                                           "__PORTAL_CSS__"     => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static/css',
                                           "__PORTAL_IMAGES__"  => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static/images',
                                           "__PORTAL_FONTS__"   => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static/fonts',
                                           "__PORTAL_LIBS__"    => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static/libs',
                                           "__PORTAL_PLUGINS__" => $this->resourcePrefix
                                                                  . 'theme/portal/'
                                                                  . config( 'theme.portal_theme' )
                                                                  . '/public/static/plugins'
                                         ] );

    parent::_initialize(); // TODO: Change the autogenerated stub
  }

}
