<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/26
 * Time: 15:39
 */

namespace app\admin\model\facade;


use think\Facade;

class AdminMenu extends Facade {
  protected static function getFacadeClass() {
    //parent::getFacadeClass(); // TODO: Change the autogenerated stub
    return 'app\admin\model\AdminMenu';
  }
}
